version: '2.2'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - xpack.security.enabled=true
      - discovery.seed_hosts=172.28.1.4,172.28.1.7
      - cluster.initial_master_nodes=172.28.1.3,172.28.1.4,172.28.1.7
      - "ELASTIC_USER=elastic"
      - "ELASTIC_PASSWORD=changeme"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
        #- ./config/elasticsearch.yml:/usr/share/elasticsearch/config/certs/elasticsearch.yml
        - /home/elk/es01_data:/usr/share/elasticsearch/data:rw

    ports:
      - 9200:9200
    networks:
        elastic:
          ipv4_address: 172.28.1.3

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - xpack.security.enabled=true
      - discovery.seed_hosts=172.28.1.3,172.28.1.7
      - cluster.initial_master_nodes=172.28.1.3,172.28.1.4,172.28.1.7
      - "ELASTIC_USER=elastic"
      - "ELASTIC_PASSWORD=changeme"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      #- ./config/elasticsearch.yml:/usr/share/elasticsearch/config/certs/elasticsearch.yml
      - /home/elk/es02_data:/usr/share/elasticsearch/data:rw
    networks:
        elastic:
          ipv4_address: 172.28.1.4

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - xpack.security.enabled=true
      - discovery.seed_hosts=172.28.1.3,172.28.1.4
      - cluster.initial_master_nodes=172.28.1.3,172.28.1.4,172.28.1.7
      - "ELASTIC_USER=elastic"
      - "ELASTIC_PASSWORD=changeme"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      #- ./config/elasticsearch.yml:/usr/share/elasticsearch/config/certs/elasticsearch.yml
      - /home/elk/es03_data:/usr/share/elasticsearch/data:rw
    networks:
        elastic:
          ipv4_address: 172.28.1.7

  kib01:
    image: docker.elastic.co/kibana/kibana:7.6.1
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://172.28.1.3:9200
      ELASTICSEARCH_HOSTS: http://172.28.1.3:9200
    volumes:
        - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
        elastic:
          ipv4_address: 172.28.1.5
    depends_on:
      - es01
    restart: unless-stopped

  logs01:
    image: docker.elastic.co/logstash/logstash:7.6.1
    container_name: logs01
    ports:
        - 5044:5044
        - 42262:42262
    environment:
      ELASTICSEARCH_URL: http://172.28.1.3:9200
      ELASTICSEARCH_HOSTS: http://172.28.1.3:9200

    ulimits:
        memlock:
            soft: -1
            hard: -1
    volumes:
        - ./config/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
        - ./config/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    networks:
        elastic:
          ipv4_address: 172.28.1.6
    depends_on:
      - es01
    restart: unless-stopped

networks:
    elastic:
        driver: bridge
        ipam:
            config:
              - subnet: "172.28.0.0/16"
                gateway: "172.28.0.1"
