---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.js
#
server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ "http://172.28.1.3:9200", "http://172.28.1.4:9201", "http://172.28.1.7:9202" ]
xpack.monitoring.ui.container.elasticsearch.enabled: true
xpack.monitoring.kibana.collection.enabled: false
logging.verbose: true
## X-Pack security credentials
elasticsearch.username: elastic
elasticsearch.password: changeme
